app:
  image: amara-app
  entrypoint: ["/usr/local/bin/run"]
  environment:
    DJANGO_SETTINGS_MODULE: dev_settings
    DJANGO_LIVE_TEST_SERVER_ADDRESS: 'localhost:8081,8090-8100,9000-9200'
    LANG: en_US.UTF-8
    WORKERS: 2
    # Uncomment to test out the json logs that we use on production
    # JSON_LOGGING: 1
  volumes:
    - .:/opt/apps/unisubs
  hostname: unisubs.example.com
  ports:
    - "8000:8000"
  links:
    - db
    - queue
    - cache

worker:
  image: amara-app
  entrypoint: ["/usr/bin/env"]
  command: /usr/bin/python manage.py celery worker -Q celery,feeds --scheduler=djcelery.schedulers.DatabaseScheduler -B -E
  environment:
    DJANGO_SETTINGS_MODULE: dev_settings
    LANG: en_US.UTF-8
    # Uncomment to test out the json logs that we use on production
    # JSON_LOGGING: 1
  volumes:
    - .:/opt/apps/unisubs
  links:
    - db
    - queue
    - cache

db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: amara
    MYSQL_USER: amara
    MYSQL_PASSWORD: amara
    MYSQL_DATABASE: amara
  volumes:
    - ./docker-dev/mysql/conf.d/:/etc/mysql/conf.d
  ports:
    - "3306"

queue:
  image: amara/rabbitmq
  ports:
    - "5672"
    - "15672"

cache:
  image: amara/memcached
  ports:
    - "11211"
